# Generated by Django 5.0.3 on 2024-06-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Product_images',
            new_name='Product_image',
        ),
    ]
