# Generated by Django 5.0.3 on 2024-06-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_products_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
