# Generated by Django 5.0.3 on 2024-06-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_image_product_main_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_image',
            new_name='ProductImage',
        ),
    ]
