# Generated by Django 5.0.3 on 2024-06-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_product_image_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
