# Generated by Django 5.0.3 on 2024-06-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='other_images/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='other_images',
            field=models.ManyToManyField(to='api.productimage'),
        ),
    ]
