# Generated by Django 5.0.3 on 2024-06-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
