# Generated by Django 5.0.3 on 2024-06-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
