# Generated by Django 5.0.3 on 2024-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
