# Generated by Django 5.0.3 on 2024-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
