# Generated by Django 5.0.3 on 2024-06-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
