# Generated by Django 5.0.3 on 2024-06-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
